export const SURF_TUNING = {
  gravity: 19.5,
  airAcceleration: 2.35,
  maxWishSpeed: 17,
  platformMoveSpeed: 18,
  platformAcceleration: 14,
  platformFriction: 9,
  platformStopSpeed: 6,
  jumpSpeed: 8.5,
  rampFriction: 0.008,
  rampMouseSteeringResponse: 10,
  rampMouseMaximumTurnRate: 4.2,
  rampAttachmentAcceleration: 14,
  rampAttachmentSeparationResponse: 18,
  rampAttachmentGraceTime: 0.22,
  safetySpeedLimit: 320,
  velocityGaugeSpeed: 120,

  surfaceSnapDistance: 1.16,
  surfacePenetrationTolerance: 0.44,
  surfaceEdgeCatchDepth: 1.2,
  surfaceSweepPadding: 0.2,
  rampUndersideCollisionPadding: 0.035,
  rampSideCollisionPadding: 0.035,
  rampBoundsForgiveness: 0.5,
  contactGraceTime: 0.14,
  contactGraceBounds: 0.76,
  contactGraceDistance: 1.2,
  contactSnapSpeed: 11,
  contactSeparationSpeed: 2.5,

  resetHeight: -96,
  resetDropDistance: 12,
  minimumLandingContactTime: 0.16,
  landingDrag: 0.12,
  completionDrag: 0.2,

  cameraSensitivity: 0.0015,
  cameraPitchLimit: 0.58,
  cameraRollMaximum: 0.075,
  cameraRollVelocityScale: 0.0024,
  cameraRollSurfaceScale: 0.042,
  cameraRollResponse: 9.5,
  baseFov: 73,
  maxFov: 90,
  fovStartSpeed: 15,
  fovSpeedGain: 0.8,
  fovResponse: 6.8,

  fixedStep: 1 / 120,
  maxFrameDelta: 0.05,
  maxSubsteps: 8,
  playerHeight: 1.5,
  playerRadius: 0.42,
  telemetryInterval: 0.06,
} as const;
